const ENTITY = {
	
	MESSAGE: 'message',
	POLL: 'poll',
	POLLPRIMARY: 'pollprimary',
	POLLSECONDARY: 'pollsecondary',
	TRANSITION: 'transition',
	DISERTANTS: 'disertants',
	MATERIALS: 'materials',
	SPONSORS: 'sponsors',
	TYPE: 'type',
	SPECIALTY: 'specialty',
	PROPERTY: 'property',
	COUNTRY: 'country',
	PROPERTYTYPE: 'propertyType',
	AGENT: 'agent',
	STATE: 'state',
	LOCATION: 'location',
	COUNTRYITEM: 'countryItem',
	PROPERTYTAG: 'propertyTag',
	LOGIN: 'login',
	REGISTER: 'register',
	RESETPASS: 'resetPass',
	REQUESTRESET: 'requestReset',
	RESET: 'reset',
	PROPERTYDETAILS: 'propertyDetails',
	APPLY: 'apply',
	PHONECALL: 'phonecall',
	NEWSLETTER: 'newsletter',
	POST: 'post',
	AUTHOR: 'author',
	COMMENT: 'comment',
	CATEGORY: 'category',
	LIKE: 'like',
	RELATEDPOSTS: 'relatedPosts',
	FEATURE: 'feature',
	CONFIGURATION: 'configuration',
	USER: 'user',
	DEVELOPMENT: 'development',
	
	EVENT: 'event',
	SUBAGENT: 'subagent',
	CLIENTS: 'clients',
	SATISFIEDCUSTOMERS: 'satisfiedCustomers',
	DEVELOPMENTDETAILS: 'developmentDetails',
	NEW_ENTITY: 'useless text',
}

const entities = {
	MESSAGE: {
		ENTITY: ENTITY.MESSAGE,
		ENTITY_MAYUS: ENTITY.MESSAGE.toUpperCase(),
		ENTITY_PLURAL: ENTITY.MESSAGE + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.MESSAGE + 's').toUpperCase(),
		ENTITY_CAMEL_CASE: ENTITY.MESSAGE.toUpperCase() + ENTITY.MESSAGE.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.MESSAGE + 's').toUpperCase() + (ENTITY.MESSAGE + 's').slice(1),
	},
	POLL: {
		ENTITY: ENTITY.POLL,
		ENTITY_MAYUS: ENTITY.POLL.toUpperCase(),
		ENTITY_PLURAL: ENTITY.POLL + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.POLL + 's').toUpperCase(),
		ENTITY_CAMEL_CASE: ENTITY.POLL.toUpperCase() + ENTITY.POLL.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.POLL + 's').toUpperCase() + (ENTITY.POLL + 's').slice(1),
		SET_ENTITY_MAYUS_WITH_AUTH:
			'SET_' + (ENTITY.POLL + 's').toUpperCase() + '_WITH_AUTH',
		REINTENTAR_ENTITY_MAYUS: 'REINTENTAR_' + ENTITY.POLL.toUpperCase(),
	},
	POLLPRIMARY: {
		ENTITY: ENTITY.POLLPRIMARY,
		ENTITY_MAYUS: ENTITY.POLLPRIMARY.toUpperCase(),
		ENTITY_PLURAL: ENTITY.POLLPRIMARY + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.POLLPRIMARY + 's').toUpperCase(),
		ENTITY_CAMEL_CASE: ENTITY.POLLPRIMARY.toUpperCase() + ENTITY.POLLPRIMARY.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.POLLPRIMARY + 's').toUpperCase() + (ENTITY.POLLPRIMARY + 's').slice(1),
		SET_ENTITY_MAYUS_WITH_AUTH:
			'SET_' + (ENTITY.POLLPRIMARY + 's').toUpperCase() + '_WITH_AUTH',
		REINTENTAR_ENTITY_MAYUS: 'REINTENTAR_' + ENTITY.POLLPRIMARY.toUpperCase(),
	},
	POLLSECONDARY: {
		ENTITY: ENTITY.POLLSECONDARY,
		ENTITY_MAYUS: ENTITY.POLLSECONDARY.toUpperCase(),
		ENTITY_PLURAL: ENTITY.POLLSECONDARY + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.POLLSECONDARY + 's').toUpperCase(),
		ENTITY_CAMEL_CASE: ENTITY.POLLSECONDARY.toUpperCase() + ENTITY.POLLSECONDARY.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.POLLSECONDARY + 's').toUpperCase() + (ENTITY.POLLSECONDARY + 's').slice(1),
		SET_ENTITY_MAYUS_WITH_AUTH:
			'SET_' + (ENTITY.POLLSECONDARY + 's').toUpperCase() + '_WITH_AUTH',
		REINTENTAR_ENTITY_MAYUS: 'REINTENTAR_' + ENTITY.POLLSECONDARY.toUpperCase(),
	},
	TRANSITION: {
		ENTITY: ENTITY.TRANSITION,
		ENTITY_MAYUS: ENTITY.TRANSITION.toUpperCase(),
		ENTITY_PLURAL: ENTITY.TRANSITION + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.TRANSITION + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.TRANSITION.toUpperCase() + ENTITY.TRANSITION.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.TRANSITION + 's').toUpperCase() +
			(ENTITY.TRANSITION + 's').slice(1),
	},
	DISERTANTS: {
		ENTITY: ENTITY.DISERTANTS,
		ENTITY_MAYUS: ENTITY.DISERTANTS.toUpperCase(),
		ENTITY_PLURAL: ENTITY.DISERTANTS + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.DISERTANTS + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.DISERTANTS.toUpperCase() + ENTITY.DISERTANTS.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.DISERTANTS + 's').toUpperCase() +
			(ENTITY.DISERTANTS + 's').slice(1),
	},
	MATERIALS: {
		ENTITY: ENTITY.MATERIALS,
		ENTITY_MAYUS: ENTITY.MATERIALS.toUpperCase(),
		ENTITY_PLURAL: ENTITY.MATERIALS + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.MATERIALS + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.MATERIALS.toUpperCase() + ENTITY.MATERIALS.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.MATERIALS + 's').toUpperCase() +
			(ENTITY.DISERTANTS + 's').slice(1),
	},
	SPONSORS: {
		ENTITY: ENTITY.SPONSORS,
		ENTITY_MAYUS: ENTITY.SPONSORS.toUpperCase(),
		ENTITY_PLURAL: ENTITY.SPONSORS + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.SPONSORS + 's').toUpperCase(),
		ENTITY_CAMEL_CASE: ENTITY.SPONSORS.toUpperCase() + ENTITY.SPONSORS.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.SPONSORS + 's').toUpperCase() + (ENTITY.SPONSORS + 's').slice(1),
	},
	TYPE: {
		ENTITY: ENTITY.TYPE,
		ENTITY_MAYUS: ENTITY.TYPE.toUpperCase(),
		ENTITY_PLURAL: ENTITY.TYPE + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.TYPE + 's').toUpperCase(),
		ENTITY_CAMEL_CASE: ENTITY.TYPE.toUpperCase() + ENTITY.TYPE.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.TYPE + 's').toUpperCase() + (ENTITY.TYPE + 's').slice(1),
	},
	SPECIALTY: {
		ENTITY: ENTITY.SPECIALTY,
		ENTITY_MAYUS: ENTITY.SPECIALTY.toUpperCase(),
		ENTITY_PLURAL: ENTITY.SPECIALTY + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.SPECIALTY + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.SPECIALTY.toUpperCase() + ENTITY.SPECIALTY.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.SPECIALTY + 's').toUpperCase() +
			(ENTITY.SPECIALTY + 's').slice(1),
	},
	PROPERTY: {
		ENTITY: ENTITY.PROPERTY,
		ENTITY_MAYUS: ENTITY.PROPERTY.toUpperCase(),
		ENTITY_PLURAL: ENTITY.PROPERTY + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.PROPERTY + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.PROPERTY.toUpperCase() + ENTITY.PROPERTY.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.PROPERTY + 's').toUpperCase() +
			(ENTITY.PROPERTY + 's').slice(1),
	},
	COUNTRY: {
		ENTITY: ENTITY.COUNTRY,
		ENTITY_MAYUS: ENTITY.COUNTRY.toUpperCase(),
		ENTITY_PLURAL: ENTITY.COUNTRY + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.COUNTRY + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.COUNTRY.toUpperCase() + ENTITY.COUNTRY.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.COUNTRY + 's').toUpperCase() +
			(ENTITY.COUNTRY + 's').slice(1),
	},
	PROPERTYTYPE: {
		ENTITY: ENTITY.PROPERTYTYPE,
		ENTITY_MAYUS: ENTITY.PROPERTYTYPE.toUpperCase(),
		ENTITY_PLURAL: ENTITY.PROPERTYTYPE + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.PROPERTYTYPE + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.PROPERTYTYPE.toUpperCase() + ENTITY.PROPERTYTYPE.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.PROPERTYTYPE + 's').toUpperCase() +
			(ENTITY.PROPERTYTYPE + 's').slice(1),
	},
	AGENT: {
		ENTITY: ENTITY.AGENT,
		ENTITY_MAYUS: ENTITY.AGENT.toUpperCase(),
		ENTITY_PLURAL: ENTITY.AGENT + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.AGENT + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.AGENT.toUpperCase() + ENTITY.AGENT.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.AGENT + 's').toUpperCase() +
			(ENTITY.AGENT + 's').slice(1),
	},
	STATE: {
		ENTITY: ENTITY.STATE,
		ENTITY_MAYUS: ENTITY.STATE.toUpperCase(),
		ENTITY_PLURAL: ENTITY.STATE + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.STATE + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.STATE.toUpperCase() + ENTITY.STATE.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.STATE + 's').toUpperCase() +
			(ENTITY.STATE + 's').slice(1),
	},
	LOCATION: {
		ENTITY: ENTITY.LOCATION,
		ENTITY_MAYUS: ENTITY.LOCATION.toUpperCase(),
		ENTITY_PLURAL: ENTITY.LOCATION + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.LOCATION + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.LOCATION.toUpperCase() + ENTITY.LOCATION.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.LOCATION + 's').toUpperCase() +
			(ENTITY.LOCATION + 's').slice(1),
	},
	COUNTRYITEM: {
		ENTITY: ENTITY.COUNTRYITEM,
		ENTITY_MAYUS: ENTITY.COUNTRYITEM.toUpperCase(),
		ENTITY_PLURAL: ENTITY.COUNTRYITEM + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.COUNTRYITEM + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.COUNTRYITEM.toUpperCase() + ENTITY.COUNTRYITEM.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.COUNTRYITEM + 's').toUpperCase() +
			(ENTITY.COUNTRYITEM + 's').slice(1),
	},
	PROPERTYTAG: {
		ENTITY: ENTITY.PROPERTYTAG,
		ENTITY_MAYUS: ENTITY.PROPERTYTAG.toUpperCase(),
		ENTITY_PLURAL: ENTITY.PROPERTYTAG + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.PROPERTYTAG + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.PROPERTYTAG.toUpperCase() + ENTITY.PROPERTYTAG.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.PROPERTYTAG + 's').toUpperCase() +
			(ENTITY.PROPERTYTAG + 's').slice(1),
	},
	
	LOGIN: {
		ENTITY: ENTITY.LOGIN,
		ENTITY_MAYUS: ENTITY.LOGIN.toUpperCase(),
		ENTITY_PLURAL: ENTITY.LOGIN + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.LOGIN + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.LOGIN.toUpperCase() + ENTITY.LOGIN.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.LOGIN + 's').toUpperCase() +
			(ENTITY.LOGIN + 's').slice(1),
	},
	REGISTER: {
		ENTITY: ENTITY.REGISTER,
		ENTITY_MAYUS: ENTITY.REGISTER.toUpperCase(),
		ENTITY_PLURAL: ENTITY.REGISTER + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.REGISTER + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.REGISTER.toUpperCase() + ENTITY.REGISTER.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.REGISTER + 's').toUpperCase() +
			(ENTITY.REGISTER + 's').slice(1),
	},
	RESETPASS: {
		ENTITY: ENTITY.RESETPASS,
		ENTITY_MAYUS: ENTITY.RESETPASS.toUpperCase(),
		ENTITY_PLURAL: ENTITY.RESETPASS + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.RESETPASS + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.RESETPASS.toUpperCase() + ENTITY.RESETPASS.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.RESETPASS + 's').toUpperCase() +
			(ENTITY.RESETPASS + 's').slice(1),
	},
	REQUESTRESET: {
		ENTITY: ENTITY.REQUESTRESET,
		ENTITY_MAYUS: ENTITY.REQUESTRESET.toUpperCase(),
		ENTITY_PLURAL: ENTITY.REQUESTRESET + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.REQUESTRESET + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.REQUESTRESET.toUpperCase() + ENTITY.REQUESTRESET.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.REQUESTRESET + 's').toUpperCase() +
			(ENTITY.REQUESTRESET + 's').slice(1),
	},
	RESET: {
		ENTITY: ENTITY.RESET,
		ENTITY_MAYUS: ENTITY.RESET.toUpperCase(),
		ENTITY_PLURAL: ENTITY.RESET + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.RESET + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.RESET.toUpperCase() + ENTITY.RESET.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.RESET + 's').toUpperCase() +
			(ENTITY.RESET + 's').slice(1),
	},


	PROPERTYDETAILS: {
		ENTITY: ENTITY.PROPERTYDETAILS,
		ENTITY_MAYUS: ENTITY.PROPERTYDETAILS.toUpperCase(),
		ENTITY_PLURAL: ENTITY.PROPERTYDETAILS + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.PROPERTYDETAILS + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.PROPERTYDETAILS.toUpperCase() + ENTITY.PROPERTYDETAILS.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.PROPERTYDETAILS + 's').toUpperCase() +
			(ENTITY.PROPERTYDETAILS + 's').slice(1),
	},
	APPLY: {
		ENTITY: ENTITY.APPLY,
		ENTITY_MAYUS: ENTITY.APPLY.toUpperCase(),
		ENTITY_PLURAL: ENTITY.APPLY + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.APPLY + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.APPLY.toUpperCase() + ENTITY.APPLY.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.APPLY + 's').toUpperCase() +
			(ENTITY.APPLY + 's').slice(1),
	},
	PHONECALL: {
		ENTITY: ENTITY.PHONECALL,
		ENTITY_MAYUS: ENTITY.PHONECALL.toUpperCase(),
		ENTITY_PLURAL: ENTITY.PHONECALL + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.PHONECALL + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.PHONECALL.toUpperCase() + ENTITY.PHONECALL.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.PHONECALL + 's').toUpperCase() +
			(ENTITY.PHONECALL + 's').slice(1),
	},
	NEWSLETTER: {
		ENTITY: ENTITY.NEWSLETTER,
		ENTITY_MAYUS: ENTITY.NEWSLETTER.toUpperCase(),
		ENTITY_PLURAL: ENTITY.NEWSLETTER + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.NEWSLETTER + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.NEWSLETTER.toUpperCase() + ENTITY.NEWSLETTER.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.NEWSLETTER + 's').toUpperCase() +
			(ENTITY.NEWSLETTER + 's').slice(1),
	},
	POST: {
		ENTITY: ENTITY.POST,
		ENTITY_MAYUS: ENTITY.POST.toUpperCase(),
		ENTITY_PLURAL: ENTITY.POST + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.POST + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.POST.toUpperCase() + ENTITY.POST.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.POST + 's').toUpperCase() +
			(ENTITY.POST + 's').slice(1),
	},
	AUTHOR: {
		ENTITY: ENTITY.AUTHOR,
		ENTITY_MAYUS: ENTITY.AUTHOR.toUpperCase(),
		ENTITY_PLURAL: ENTITY.AUTHOR + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.AUTHOR + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.AUTHOR.toUpperCase() + ENTITY.AUTHOR.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.AUTHOR + 's').toUpperCase() +
			(ENTITY.AUTHOR + 's').slice(1),
	},
	COMMENT: {
		ENTITY: ENTITY.COMMENT,
		ENTITY_MAYUS: ENTITY.COMMENT.toUpperCase(),
		ENTITY_PLURAL: ENTITY.COMMENT + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.COMMENT + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.COMMENT.toUpperCase() + ENTITY.COMMENT.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.COMMENT + 's').toUpperCase() +
			(ENTITY.COMMENT + 's').slice(1),
	},
	CATEGORY: {
		ENTITY: ENTITY.CATEGORY,
		ENTITY_MAYUS: ENTITY.CATEGORY.toUpperCase(),
		ENTITY_PLURAL: ENTITY.CATEGORY + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.CATEGORY + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.CATEGORY.toUpperCase() + ENTITY.CATEGORY.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.CATEGORY + 's').toUpperCase() +
			(ENTITY.CATEGORY + 's').slice(1),
	},
	LIKE: {
		ENTITY: ENTITY.LIKE,
		ENTITY_MAYUS: ENTITY.LIKE.toUpperCase(),
		ENTITY_PLURAL: ENTITY.LIKE + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.LIKE + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.LIKE.toUpperCase() + ENTITY.LIKE.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.LIKE + 's').toUpperCase() +
			(ENTITY.LIKE + 's').slice(1),
	},
	RELATEDPOSTS: {
		ENTITY: ENTITY.RELATEDPOSTS,
		ENTITY_MAYUS: ENTITY.RELATEDPOSTS.toUpperCase(),
		ENTITY_PLURAL: ENTITY.RELATEDPOSTS + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.RELATEDPOSTS + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.RELATEDPOSTS.toUpperCase() + ENTITY.RELATEDPOSTS.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.RELATEDPOSTS + 's').toUpperCase() +
			(ENTITY.RELATEDPOSTS + 's').slice(1),
	},
	FEATURE: {
		ENTITY: ENTITY.FEATURE,
		ENTITY_MAYUS: ENTITY.FEATURE.toUpperCase(),
		ENTITY_PLURAL: ENTITY.FEATURE + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.FEATURE + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.FEATURE.toUpperCase() + ENTITY.FEATURE.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.FEATURE + 's').toUpperCase() +
			(ENTITY.FEATURE + 's').slice(1),
	},
	CONFIGURATION: {
		ENTITY: ENTITY.CONFIGURATION,
		ENTITY_MAYUS: ENTITY.CONFIGURATION.toUpperCase(),
		ENTITY_PLURAL: ENTITY.CONFIGURATION + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.CONFIGURATION + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.CONFIGURATION.toUpperCase() + ENTITY.CONFIGURATION.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.CONFIGURATION + 's').toUpperCase() +
			(ENTITY.CONFIGURATION + 's').slice(1),
	},
	USER: {
		ENTITY: ENTITY.USER,
		ENTITY_MAYUS: ENTITY.USER.toUpperCase(),
		ENTITY_PLURAL: ENTITY.USER + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.USER + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.USER.toUpperCase() + ENTITY.USER.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.USER + 's').toUpperCase() +
			(ENTITY.USER + 's').slice(1),
	},
	DEVELOPMENT: {
		ENTITY: ENTITY.DEVELOPMENT,
		ENTITY_MAYUS: ENTITY.DEVELOPMENT.toUpperCase(),
		ENTITY_PLURAL: ENTITY.DEVELOPMENT + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.DEVELOPMENT + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.DEVELOPMENT.toUpperCase() + ENTITY.DEVELOPMENT.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.DEVELOPMENT + 's').toUpperCase() +
			(ENTITY.DEVELOPMENT + 's').slice(1),
	},
	
	EVENT: {
		ENTITY: ENTITY.EVENT,
		ENTITY_MAYUS: ENTITY.EVENT.toUpperCase(),
		ENTITY_PLURAL: ENTITY.EVENT + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.EVENT + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.EVENT.toUpperCase() + ENTITY.EVENT.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.EVENT + 's').toUpperCase() +
			(ENTITY.EVENT + 's').slice(1),
	},
	SUBAGENT: {
		ENTITY: ENTITY.SUBAGENT,
		ENTITY_MAYUS: ENTITY.SUBAGENT.toUpperCase(),
		ENTITY_PLURAL: ENTITY.SUBAGENT + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.SUBAGENT + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.SUBAGENT.toUpperCase() + ENTITY.SUBAGENT.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.SUBAGENT + 's').toUpperCase() +
			(ENTITY.SUBAGENT + 's').slice(1),
	},

	SATISFIEDCUSTOMERS: {
		ENTITY: ENTITY.SATISFIEDCUSTOMERS,
		ENTITY_MAYUS: ENTITY.SATISFIEDCUSTOMERS.toUpperCase(),
		ENTITY_PLURAL: ENTITY.SATISFIEDCUSTOMERS + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.SATISFIEDCUSTOMERS + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.SATISFIEDCUSTOMERS.toUpperCase() + ENTITY.SATISFIEDCUSTOMERS.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.SATISFIEDCUSTOMERS + 's').toUpperCase() +
			(ENTITY.SATISFIEDCUSTOMERS + 's').slice(1),
	},
	DEVELOPMENTDETAILS: {
		ENTITY: ENTITY.DEVELOPMENTDETAILS,
		ENTITY_MAYUS: ENTITY.DEVELOPMENTDETAILS.toUpperCase(),
		ENTITY_PLURAL: ENTITY.DEVELOPMENTDETAILS + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.DEVELOPMENTDETAILS + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.DEVELOPMENTDETAILS.toUpperCase() + ENTITY.DEVELOPMENTDETAILS.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.DEVELOPMENTDETAILS + 's').toUpperCase() +
			(ENTITY.DEVELOPMENTDETAILS + 's').slice(1),
	},
	NEW_ENTITY: {
		ENTITY: ENTITY.NEW_ENTITY,
		ENTITY_MAYUS: ENTITY.NEW_ENTITY.toUpperCase(),
		ENTITY_PLURAL: ENTITY.NEW_ENTITY + 's',
		ENTITY_MAYUS_PLURAL: (ENTITY.NEW_ENTITY + 's').toUpperCase(),
		ENTITY_CAMEL_CASE:
			ENTITY.NEW_ENTITY.toUpperCase() + ENTITY.NEW_ENTITY.slice(1),
		ENTITY_CAMEL_CASE_PLURAL:
			(ENTITY.NEW_ENTITY + 's').toUpperCase() +
			(ENTITY.NEW_ENTITY + 's').slice(1),
	},
	//ADD NEW ENTITY HERE
}

export default entities
